package com.atguigu.mapper;

import com.atguigu.bean.SysOrganization;
import java.util.List;

public interface SysOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Tue Apr 24 12:42:01 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Tue Apr 24 12:42:01 CST 2018
     */
    int insert(SysOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Tue Apr 24 12:42:01 CST 2018
     */
    SysOrganization selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Tue Apr 24 12:42:01 CST 2018
     */
    List<SysOrganization> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_organization
     *
     * @mbggenerated Tue Apr 24 12:42:01 CST 2018
     */
    int updateByPrimaryKey(SysOrganization record);
}